baseURL: "https://gbruno16.github.io" 
title: Giuseppe Bruno
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Books
          url: books/
          weight: 5 
        - name: Papers
          url: papers/
          weight: 2
        - name: Courses
          url: courses/
          weight: 3
        - name: Data
          url: data/
          weight: 4 
        - name: Blog
          url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
          weight: 6

params:
    description: "This website hosts Giuseppe Bruno's research papers, books, course materials, data, curriculum vitae, and contact information."
    author: Giuseppe Bruno
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "May 2025"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Giuseppe Bruno
          subtitle: "Hi! I’m Giuseppe Bruno, a PhD student at the University of Bern (IMSV). I earned my Master’s degree in 2024 from the University of Pisa, after an exchange semester at the University of Bonn. I’m excited about the mathematical foundations of machine learning, particularly mean-field models for Transformers and large language models."
          imageUrl: "profile.png"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Papers
              url: papers/
            - name: Projects
              url: projects/
            - name: CV
              url: cv/
            
    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:giuseppe.bruno@unibe.ch
        - name: Location
          url: location/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=gbruno16
        - name: GitHub
          url: https://github.com/gbruno16
  
    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Giuseppe Bruno"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2